job:
  fits_name: "m1_n.fits"
  pos_ra: 155.66367
  pos_dec: -30.7130
  random_position: True
  image_size: [256]
  data_path: "./data/radio_interferometry"
  use_gpus: True
  number_of_time_steps: 512
  start_frequency_hz: 100e6
  end_frequency_hz: 120e6
  number_of_channels: 12
  add_noise: False

singularity:
  image_path: "karabo.sif"  # Relative to project root
  mount_point: "/workspace"
  # Directory inside container where the command runs
  working_dir: "/workspace/benchmark_invprob_inference"

slurm:
  folder: "debug_output/slurm_logs"
  job_name: "karabo_simulator"
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 40
  gres: "gpu:4"
  time: 60 # in minutes
  hint: "nomultithread"
  account: # Setup your account here
  constraint: "v100-32g"
  poll_interval_seconds: 30
  wait_timeout_seconds: 1200
  setup:
    - "module purge"
    - "module load singularity"
    - "set -x"
