objective:
  - reconstruction_objective

dataset:
  - radio_interferometry:
      image_size: 256
      noise_level: 0.1

solver:
  - PnP:
      denoiser: drunet
      denoiser_sigma: 0.1
      distribute_physics: False
      distribute_denoiser: False
      init_method: 'zeros'
      step_size_scale: 0.9
      
